# Generated by Django 6.0.7 on 2026-07-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailableServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Server display name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.FilePathField(
                        allow_folders=True,
                        blank=True,
                        null=True,
                        path="~/minecraft",
                        recursive=True,
                        verbose_name="Server file path",
                    ),
                ),
                (
                    "hostname",
                    models.TextField(blank=True, null=True, verbose_name="Server URL"),
                ),
                (
                    "port",
                    models.IntegerField(blank=True, null=True, verbose_name="RPC port"),
                ),
                (
                    "api_key",
                    models.TextField(blank=True, null=True, verbose_name="RPC API key"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
