# Generated by Django 6.0.7 on 2026-07-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availableserver",
            name="api_key",
            field=models.CharField(blank=True, null=True, verbose_name="RPC API key"),
        ),
        migrations.AlterField(
            model_name="availableserver",
            name="hostname",
            field=models.CharField(blank=True, null=True, verbose_name="Server URL"),
        ),
        migrations.AlterField(
            model_name="availableserver",
            name="name",
            field=models.CharField(verbose_name="Server display name"),
        ),
    ]
