# Generated by Django 6.0.7 on 2026-07-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0002_fix_string_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availableserver",
            name="hostname",
            field=models.CharField(blank=True, null=True, verbose_name="Server domain"),
        ),
        migrations.AlterField(
            model_name="availableserver",
            name="path",
            field=models.FilePathField(
                blank=True,
                match="server.properties",
                null=True,
                path="/home/iota/minecraft",
                recursive=True,
                verbose_name="Server file path",
            ),
        ),
    ]
