# Generated by Django 6.0.7 on 2026-07-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_alter_availableserver_hostname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availableserver",
            name="path",
            field=models.FilePathField(
                blank=True,
                match="server.properties",
                null=True,
                path="/home/server/minecraft",
                recursive=True,
                verbose_name="Server file path",
            ),
        ),
    ]
